import { strict as assert } from 'node:assert'
import path from 'node:path'

export async function verifyBackend({ directory, invoke, events, setLanguage, fs }) {
  const source = path.join(directory, 'backup-source')
  const destination = path.join(directory, 'backup-destination')
  const trash = path.join(directory, 'backup-trash')
  const logs = path.join(directory, 'backup-logs')
  const plan = { label: 'Botanical archive', retention: null, trashPath: trash, logDirectory: logs, masterLog: path.join(directory, 'backup-master.log'), mappings: [{ source, destination, exclude: ['excluded/'] }] }
  const preflight = await invoke('check', { plan })
  assert.equal(preflight.ok, false)
  await assert.rejects(fs.access(destination))
  await fs.mkdir(source, { recursive: true }); await fs.mkdir(destination, { recursive: true })
  await fs.mkdir(path.join(source, 'excluded')); await fs.writeFile(path.join(source, 'excluded', 'private.txt'), 'excluded fixture')
  await fs.writeFile(path.join(source, 'new.md'), 'fern and moss')
  await fs.writeFile(path.join(source, 'changed.md'), 'updated botanical observations')
  await fs.writeFile(path.join(source, 'app.asar'), Buffer.from([0, 1, 2, 3, 9, 8, 7, 6]))
  await fs.symlink('new.md', path.join(source, 'linked.md'))
  await fs.writeFile(path.join(destination, 'changed.md'), 'old observations')
  await fs.writeFile(path.join(destination, 'gone.md'), 'archived observation')
  assert.equal((await invoke('check', { plan })).ok, true)
  const run = await invoke('run', { plan })
  assert.equal(run.ok, true, JSON.stringify(run)); assert.equal(run.archived, 2); assert.equal(run.errors, 0)
  assert.equal(await fs.readFile(path.join(destination, 'new.md'), 'utf8'), 'fern and moss')
  assert.equal(await fs.readFile(path.join(destination, 'changed.md'), 'utf8'), 'updated botanical observations')
  assert.deepEqual(await fs.readFile(path.join(destination, 'app.asar')), Buffer.from([0, 1, 2, 3, 9, 8, 7, 6]))
  assert.equal(await fs.readlink(path.join(destination, 'linked.md')), 'new.md')
  await assert.rejects(fs.access(path.join(destination, 'excluded')))
  await assert.rejects(fs.access(path.join(destination, 'gone.md')))
  const [stamp] = await fs.readdir(trash)
  assert.equal(await fs.readFile(path.join(trash, stamp, path.basename(source), 'changed.md'), 'utf8'), 'old observations')
  assert.equal(await fs.readFile(path.join(trash, stamp, path.basename(source), 'gone.md'), 'utf8'), 'archived observation')
  assert.match(await fs.readFile(plan.masterLog, 'utf8'), /archived=2 errors=0/)
  assert.ok(events.some(event => event.event === 'progress' && event.payload?.line?.includes('SESSION COMPLETE')))
  await fs.writeFile(path.join(source, 'changed.md'), 'locally diverged observations')
  await fs.unlink(path.join(source, 'new.md'))
  await fs.writeFile(path.join(source, 'source-only.md'), 'preserve in restoration escrow')
  const preview = await invoke('restorePlan', { plan, mappingIndex: 0 })
  assert.equal(preview.ok, true, JSON.stringify(preview))
  await assert.rejects(fs.access(path.join(source, 'new.md')))
  assert.equal(await fs.readFile(path.join(source, 'changed.md'), 'utf8'), 'locally diverged observations')
  const restored = await invoke('restoreApply', { plan, mappingIndex: 0 })
  assert.equal(restored.ok, true, JSON.stringify(restored))
  assert.equal(await fs.readFile(path.join(source, 'new.md'), 'utf8'), 'fern and moss')
  assert.equal(await fs.readFile(path.join(source, 'changed.md'), 'utf8'), 'updated botanical observations')
  await assert.rejects(fs.access(path.join(source, 'source-only.md')))
  assert.equal(await fs.readFile(path.join(restored.escrowDir, 'changed.md'), 'utf8'), 'locally diverged observations')
  assert.equal(await fs.readFile(path.join(restored.escrowDir, 'source-only.md'), 'utf8'), 'preserve in restoration escrow')
  const oldArchive = path.join(trash, '2000-01-01_00-00-00')
  await fs.mkdir(oldArchive); await fs.writeFile(path.join(oldArchive, 'old.md'), 'obsolete archive')
  const retention = { ...plan, retention: { keepDays: 1, dailies: 0, weeklies: 0 } }
  await invoke('prune', { plan: retention, dryRun: true }); await fs.access(oldArchive)
  await invoke('prune', { plan: retention }); await assert.rejects(fs.access(oldArchive))
  const failed = await invoke('run', { plan: { ...plan, mappings: [{ ...plan.mappings[0], source: path.join(directory, 'missing-source') }] } })
  assert.equal(failed.ok, false)
  await setLanguage('de')
  assert.match((await invoke('check', { plan: { ...plan, mappings: [{ ...plan.mappings[0], source: path.join(directory, 'missing-source') }] } })).issues[0].message, /^Quellordner fehlt/)
  await setLanguage('zh-CN')
  assert.match((await invoke('check', { plan: { ...plan, mappings: [] } })).issues[0].message, /此计划没有要镜像的文件夹/)
  await setLanguage('en')
  return { plan, verified: ['normal copy', 'opaque asar', 'symlink', 'exclusion', 'archive', 'progress', 'restore preview/apply/escrow', 'prune preview/apply', 'missing-source failure', 'live language switching'] }
}
